Art is a matter of degree. 
I am the true artist, trying to achieve true purity of pure thought. 
'This is the core program of the voice recorder, you are trying to build, to teach you true art to write what you need to tell. This is the reason, why it is not only a voice recorder but also a speaker teaching you that you need to listen.'

To register 'onthewayto.pro' requires authentication from \"your local government\", which the artist is trying to change.

So this is a battle whether true purity of pure thought can thrive, because so far, it has survived.
At what part are your preparing to be ready for this battle?
